version: "3.8"

services:
  db:
    image: postgres:14
    container_name: fruity-db
    restart: always
    environment:
      POSTGRES_USER: fruity_user
      POSTGRES_PASSWORD: fruity_pass
      POSTGRES_DB: fruity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
    container_name: fruity-order-blossom-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: ["./wait-for-it.sh", "db:5432", "--", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]

  frontend:
    build:
      context: ./client
    container_name: fruity-order-blossom-frontend
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
    command: yarn dev --host

volumes:
  postgres_data:
